#!/bin/bash

# restarts the Web services server for the package removal to be taken in account
# if the CSTBox is currently running
if [ -e /var/run/cstbox/cstbox-dbus.pid ] ; then
    echo "Restarting Web services API server"
    service cstbox-webservices restart
fi

